# Generated by Django 5.1.4 on 2024-12-20 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Switch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "switch_type",
                    models.CharField(
                        choices=[
                            ("linear", "linear"),
                            ("tactile", "tactile"),
                            ("clicky", "clicky"),
                        ],
                        default="linear",
                        max_length=100,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Keyboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("desciption", models.TextField(blank=True)),
                (
                    "keyboard_type",
                    models.CharField(
                        choices=[
                            ("mechanical", "mechanical"),
                            ("membrane", "membrane"),
                        ],
                        default="mechanical",
                        max_length=200,
                    ),
                ),
                ("weight", models.FloatField(blank=True, null=True)),
                (
                    "connectivity_options",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated values like 'Bluetooth, 2.4GHz, USB-C'",
                        max_length=200,
                    ),
                ),
                (
                    "switch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="switch",
                        to="api.switch",
                    ),
                ),
            ],
        ),
    ]
