# Generated by Django 5.1.4 on 2024-12-20 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="keyboard",
            old_name="desciption",
            new_name="description",
        ),
    ]
