# Generated by Django 5.1.4 on 2024-12-20 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_desciption_keyboard_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyboard",
            name="switch",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="switch",
                to="api.switch",
            ),
        ),
    ]
