# Generated by Django 5.1.4 on 2024-12-22 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_keyboard_switch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyboard",
            name="switch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="switch",
                to="api.switch",
            ),
        ),
    ]
