# Generated by Django 5.1.4 on 2024-12-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_id_alter_customuser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="user_type",
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_role",
            field=models.CharField(
                choices=[
                    ("admin", "admin"),
                    ("staff", "staff"),
                    ("customer", "customer"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
